name: bitpit
markdown: redcarpet
highlighter: rouge
baseurl: /bitpit-private


collections:
  modules:
    output: true

sections:
    modules:
        name: Modules

        subsections:
            overview:
                name: Overview
            PABLO:
                name: PABLO
            RBF:
                name: RBF

    examples:
        name: Examples

    documentation:
        name: Documentation

        subsections:
            installation:
                name: Installation
            manual:
                name: Manual

    downloads:
        name: Downloads

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed